import Post from '../../models/Post';

export default () =>
  Post.bulkCreate(
    [
      {
        title: 'Post Title',
        body: 'Post body',
        date: Date.now(),
        UserId: 1,
      },
      {
        title: 'Mrs',
        body: 'Carex tribuloides Wahlenb.',
        date: '8/22/2021',
        UserId: 7,
      },
      {
        title: 'Ms',
        body: 'Ulota D. Mohr',
        date: '5/22/2021',
        UserId: 4,
      },
      {
        title: 'Mrs',
        body: 'Minuartia groenlandica (Retz.) Ostenf.',
        date: '5/10/2022',
        UserId: 7,
      },
      {
        title: 'Honorable',
        body: 'Lopadium augustini (Tuck.) Zahlbr.',
        date: '7/31/2021',
        UserId: 4,
      },
      {
        title: 'Mrs',
        body: 'Kosteletzkya depressa (L.) O.J. Blanch., Fryxell & D.M. Bates',
        date: '4/29/2022',
        UserId: 1,
      },
      {
        title: 'Mrs',
        body: 'Cucumis prophetarum L.',
        date: '6/4/2021',
        UserId: 1,
      },
      {
        title: 'Mr',
        body: 'Arctomecon merriamii Coville',
        date: '9/19/2021',
        UserId: 2,
      },
      {
        title: 'Dr',
        body: 'Camissonia kernensis (Munz) P.H. Raven ssp. gilmanii (Munz) P.H. Raven',
        date: '12/23/2021',
        UserId: 1,
      },
      {
        title: 'Ms',
        body: 'Carex ×neorigida Lepage',
        date: '4/9/2022',
        UserId: 3,
      },
      {
        title: 'Dr',
        body: 'Brachythecium leibergii Grout',
        date: '5/7/2022',
        UserId: 5,
      },
      {
        title: 'Mr',
        body: 'Chamaesyce sparsiflora (A. Heller) Koutnik',
        date: '12/8/2021',
        UserId: 9,
      },
      {
        title: 'Honorable',
        body: 'Spiraea tomentosa L.',
        date: '3/28/2022',
        UserId: 6,
      },
      {
        title: 'Rev',
        body: 'Sabatia brevifolia Raf.',
        date: '5/15/2022',
        UserId: 4,
      },
      {
        title: 'Mrs',
        body: 'Heterotheca sessiliflora (Nutt.) Shinners ssp. echioides (Benth.) Semple var. camphorata (Eastw.) Semple',
        date: '8/25/2021',
        UserId: 5,
      },
      {
        title: 'Rev',
        body: 'Physalis heterophylla Nees',
        date: '8/20/2021',
        UserId: 2,
      },
      {
        title: 'Mrs',
        body: 'Papaver alboroseum Hultén',
        date: '10/7/2021',
        UserId: 2,
      },
      {
        title: 'Mr',
        body: 'Eriogonum eastwoodianum J.T. Howell',
        date: '7/7/2021',
        UserId: 4,
      },
      {
        title: 'Mrs',
        body: 'Hyperbaena Miers ex Benth.',
        date: '6/23/2021',
        UserId: 1,
      },
      {
        title: 'Mr',
        body: 'Holocarpha virgata (A. Gray) D.D. Keck ssp. elongata D.D. Keck',
        date: '10/26/2021',
        UserId: 7,
      },
      {
        title: 'Ms',
        body: 'Corynephorus canescens (L.) P. Beauv.',
        date: '5/19/2021',
        UserId: 6,
      },
      {
        title: 'Dr',
        body: 'Astragalus allochrous A. Gray',
        date: '8/23/2021',
        UserId: 4,
      },
      {
        title: 'Ms',
        body: 'Ephemerum cohaerens (Hedw.) Hampe',
        date: '7/18/2021',
        UserId: 4,
      },
      {
        title: 'Ms',
        body: 'Hilaria Kunth',
        date: '10/24/2021',
        UserId: 7,
      },
      {
        title: 'Mrs',
        body: 'Corylus maxima Mill.',
        date: '2/27/2022',
        UserId: 1,
      },
      {
        title: 'Ms',
        body: 'Penstemon spectabilis Thurb. ex A. Gray',
        date: '3/6/2022',
        UserId: 6,
      },
      {
        title: 'Dr',
        body: 'Paronychia jamesii Torr. & A. Gray',
        date: '10/18/2021',
        UserId: 2,
      },
      {
        title: 'Honorable',
        body: '×Sorbaronia jackii Rehder',
        date: '7/26/2021',
        UserId: 4,
      },
      {
        title: 'Mrs',
        body: 'Astragalus rusbyi Greene',
        date: '8/22/2021',
        UserId: 6,
      },
      {
        title: 'Mrs',
        body: 'Oonopsis (Nutt.) Greene',
        date: '7/18/2021',
        UserId: 8,
      },
      {
        title: 'Mr',
        body: 'Rhynchospora eximia (Nees) Boeckeler',
        date: '2/19/2022',
        UserId: 1,
      },
      {
        title: 'Honorable',
        body: 'Chamaesyce thymifolia (L.) Millsp.',
        date: '2/20/2022',
        UserId: 3,
      },
      {
        title: 'Ms',
        body: 'Dudleya pulverulenta (Nutt.) Britton & Rose',
        date: '5/1/2022',
        UserId: 4,
      },
      {
        title: 'Rev',
        body: 'Calystegia macrostegia (Greene) Brummitt ssp. tenuifolia (Abrams) Brummitt',
        date: '12/17/2021',
        UserId: 5,
      },
      {
        title: 'Mr',
        body: 'Psilotum nudum (L.) P. Beauv.',
        date: '2/22/2022',
        UserId: 5,
      },
      {
        title: 'Mr',
        body: 'Pyxine sorediata (Ach.) Mont.',
        date: '7/1/2021',
        UserId: 7,
      },
      {
        title: 'Mr',
        body: 'Acanthus syriacus Boiss.',
        date: '5/25/2021',
        UserId: 7,
      },
      {
        title: 'Dr',
        body: 'Catillaria jemtlandica Th. Fr. & Almq.',
        date: '3/7/2022',
        UserId: 3,
      },
      {
        title: 'Mrs',
        body: 'Schizaea Sm.',
        date: '8/27/2021',
        UserId: 6,
      },
      {
        title: 'Ms',
        body: 'Alchorneopsis portoricensis Urb.',
        date: '9/7/2021',
        UserId: 1,
      },
      {
        title: 'Honorable',
        body: 'Elymus alaskanus (Scribn. & Merr.) Á. Löve ssp. latiglumis (Scribn. & J.G. Sm.) Á. Löve',
        date: '11/26/2021',
        UserId: 2,
      },
      {
        title: 'Dr',
        body: 'Crataegus reverchonii Sarg.',
        date: '7/5/2021',
        UserId: 3,
      },
      {
        title: 'Ms',
        body: 'Philadelphus caucasicus Koehne [excluded]',
        date: '4/29/2022',
        UserId: 1,
      },
      {
        title: 'Rev',
        body: 'Mandragora officinarum L.',
        date: '4/11/2022',
        UserId: 1,
      },
      {
        title: 'Honorable',
        body: 'Psathyrotes ramosissima (Torr.) A. Gray',
        date: '9/4/2021',
        UserId: 7,
      },
      {
        title: 'Dr',
        body: 'Urtica gracilenta Greene',
        date: '10/3/2021',
        UserId: 4,
      },
      {
        title: 'Ms',
        body: 'Candelariella xanthostigma (Ach.) Lettau',
        date: '3/30/2022',
        UserId: 5,
      },
      {
        title: 'Rev',
        body: 'Navarretia prolifera Greene',
        date: '9/18/2021',
        UserId: 6,
      },
      {
        title: 'Ms',
        body: 'Stachys bergii G. Mulligan & D. Munro',
        date: '5/17/2021',
        UserId: 7,
      },
      {
        title: 'Dr',
        body: 'Paspalum thunbergii Kunth ex Steud.',
        date: '9/29/2021',
        UserId: 7,
      },
      {
        title: 'Rev',
        body: 'Sporastatia polyspora (Nyl.) Grummann',
        date: '6/21/2021',
        UserId: 9,
      },
      {
        title: 'Dr',
        body: 'Hibiscus furcellatus Lam.',
        date: '5/1/2022',
        UserId: 8,
      },
      {
        title: 'Dr',
        body: 'Hymenocallis liriosme (Raf.) Shinners',
        date: '1/2/2022',
        UserId: 3,
      },
      {
        title: 'Dr',
        body: 'Phyllanthus pentaphyllus C. Wright ex Griseb. ssp. pentaphyllus',
        date: '6/10/2021',
        UserId: 7,
      },
      {
        title: 'Honorable',
        body: 'Medicago heldreichii E. Small',
        date: '6/4/2021',
        UserId: 9,
      },
      {
        title: 'Dr',
        body: 'Tiarella L.',
        date: '7/28/2021',
        UserId: 9,
      },
      {
        title: 'Rev',
        body: 'Leptocoryphium Nees',
        date: '5/26/2021',
        UserId: 7,
      },
      {
        title: 'Mr',
        body: 'Stuckenia ×suecica (K. Richt.) Holub',
        date: '8/21/2021',
        UserId: 2,
      },
      {
        title: 'Rev',
        body: 'Dasylirion wheeleri S. Watson',
        date: '3/6/2022',
        UserId: 6,
      },
      {
        title: 'Ms',
        body: 'Carex hendersonii L.H. Bailey',
        date: '12/11/2021',
        UserId: 9,
      },
      {
        title: 'Rev',
        body: 'Shibataea kumasaca (Zoll. ex Steud.) Makino',
        date: '12/8/2021',
        UserId: 9,
      },
      {
        title: 'Mr',
        body: 'Carex wootonii Mack.',
        date: '12/5/2021',
        UserId: 2,
      },
      {
        title: 'Rev',
        body: 'Acer saccharinum L.',
        date: '10/29/2021',
        UserId: 3,
      },
      {
        title: 'Dr',
        body: 'Astragalus simplicifolius (Nutt.) A. Gray',
        date: '12/3/2021',
        UserId: 4,
      },
      {
        title: 'Ms',
        body: 'Didymodon rigidulus Hedw. var. icmadophilus (Schimp. ex Müll. Hal.) R.H. Zander',
        date: '2/23/2022',
        UserId: 1,
      },
      {
        title: 'Mrs',
        body: 'Eriocaulon koernickianum van Heurck & Müll. Arg.',
        date: '2/24/2022',
        UserId: 7,
      },
      {
        title: 'Ms',
        body: 'Eucalyptus laevopinea R.T. Baker',
        date: '8/29/2021',
        UserId: 1,
      },
      {
        title: 'Mrs',
        body: 'Sagittaria trifolia L.',
        date: '2/11/2022',
        UserId: 1,
      },
      {
        title: 'Honorable',
        body: 'Plecostachys serpyllifolia (P.J. Bergius) Hilliard & B.L. Burtt',
        date: '8/19/2021',
        UserId: 2,
      },
      {
        title: 'Mrs',
        body: 'Hypoxis decumbens L.',
        date: '1/22/2022',
        UserId: 1,
      },
      {
        title: 'Dr',
        body: 'Trachelospermum Lem.',
        date: '11/9/2021',
        UserId: 9,
      },
      {
        title: 'Dr',
        body: 'Rinodina applanata H. Magn.',
        date: '6/19/2021',
        UserId: 8,
      },
      {
        title: 'Mrs',
        body: 'Huperzia ×erubescens (Brack.) Holub (pro sp.)',
        date: '11/2/2021',
        UserId: 2,
      },
      {
        title: 'Dr',
        body: 'Escobaria sneedii Britton & Rose var. sneedii',
        date: '1/26/2022',
        UserId: 1,
      },
      {
        title: 'Mrs',
        body: 'Chamaecrista flexuosa (L.) Greene',
        date: '3/24/2022',
        UserId: 8,
      },
      {
        title: 'Dr',
        body: 'Systenotheca vortriedei (Brandegee) Reveal & Hardham',
        date: '2/28/2022',
        UserId: 1,
      },
      {
        title: 'Honorable',
        body: 'Erigeron leiomerus A. Gray',
        date: '6/18/2021',
        UserId: 9,
      },
      {
        title: 'Mr',
        body: 'Polygonum achoreum S.F. Blake',
        date: '10/14/2021',
        UserId: 3,
      },
      {
        title: 'Dr',
        body: 'Lolium perenne L.',
        date: '4/12/2022',
        UserId: 4,
      },
      {
        title: 'Mr',
        body: 'Lloydia Salisb. ex Rchb.',
        date: '10/15/2021',
        UserId: 1,
      },
      {
        title: 'Mrs',
        body: 'Asplenium ×herb-wagneri W.C. Taylor & Mohlenbr.',
        date: '5/18/2021',
        UserId: 9,
      },
      {
        title: 'Honorable',
        body: 'Ternstroemia peduncularis DC.',
        date: '12/7/2021',
        UserId: 1,
      },
      {
        title: 'Honorable',
        body: 'Smilax bona-nox L. var. bona-nox',
        date: '5/27/2021',
        UserId: 3,
      },
      {
        title: 'Dr',
        body: 'Aegopodium L.',
        date: '4/25/2022',
        UserId: 4,
      },
      {
        title: 'Mrs',
        body: 'Lecanora rupicola (L.) Zahlbr.',
        date: '1/27/2022',
        UserId: 6,
      },
      {
        title: 'Mrs',
        body: 'Rhododendron alabamense Rehder',
        date: '9/15/2021',
        UserId: 4,
      },
      {
        title: 'Mr',
        body: 'Eustachys petraea (Sw.) Desv.',
        date: '8/7/2021',
        UserId: 8,
      },
      {
        title: 'Mr',
        body: 'Quercus parvula Greene var. parvula',
        date: '10/25/2021',
        UserId: 1,
      },
      {
        title: 'Rev',
        body: 'Allionia incarnata L.',
        date: '5/7/2022',
        UserId: 1,
      },
      {
        title: 'Mrs',
        body: 'Geranium palmatum Cav.',
        date: '7/31/2021',
        UserId: 9,
      },
      {
        title: 'Mr',
        body: 'Triodia basedowii E. Pritz.',
        date: '10/2/2021',
        UserId: 7,
      },
      {
        title: 'Dr',
        body: 'Narcissus assoanus Dufour',
        date: '2/16/2022',
        UserId: 4,
      },
      {
        title: 'Honorable',
        body: 'Styrax redivivus (Torr.) L.C. Wheeler',
        date: '11/14/2021',
        UserId: 3,
      },
      {
        title: 'Ms',
        body: 'Carex reniformis (L.H. Bailey) Small',
        date: '10/13/2021',
        UserId: 6,
      },
      {
        title: 'Ms',
        body: 'Senecio californicus DC.',
        date: '1/8/2022',
        UserId: 2,
      },
      {
        title: 'Rev',
        body: 'Arthonia lecideella Nyl.',
        date: '7/5/2021',
        UserId: 6,
      },
      {
        title: 'Rev',
        body: 'Microseris douglasii (DC.) Sch. Bip. ssp. platycarpha (A. Gray) K.L. Chambers',
        date: '4/6/2022',
        UserId: 1,
      },
      {
        title: 'Rev',
        body: 'Ammophila champlainensis Seymour',
        date: '2/2/2022',
        UserId: 9,
      },
      {
        title: 'Honorable',
        body: 'Perityle staurophylla (Barneby) Shinners var. staurophylla',
        date: '9/9/2021',
        UserId: 5,
      },
      {
        title: 'Mrs',
        body: 'Howelliella ovata (Eastw.) Rothm.',
        date: '7/20/2021',
        UserId: 7,
      },
      {
        title: 'Mr',
        body: 'Rubus originalis L.H. Bailey',
        date: '4/26/2022',
        UserId: 7,
      },
    ],
    {
      fields: ['title', 'body', 'date', 'UserId'],
      ignoreDuplicates: true,
    },
  );
